# Default values for rhd-diagnoser.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rabbitmq:
  segmentator:
    enabled: true
  gan:
    enabled: true

bucket-storage:
  enabled: true
